mongodb:
  # MongoDB connection details
  host: 127.0.0.1
  port: 27017
  database: marketplace
  user: root
  password: ''

discord-webhook:
  hook-url: "" # Leave empty for no discord logging
  title: "MarketPlace"
  description:
    - "Buyer: {buyer}"
    - "Seller: {seller}"
    - "Item: {amount}x {item}"
    - "Bought For: ${price}"
    - "Sold For: ${earned}"
  link: ""

options:
  max-item-listings: 10 # Max number of items each player can list at a time
  black-market-item-chance: 30 # Percent change for each item to appear in the Black Market
  black-market-max-items: 50 # Maximum number of items that can appear in the Black Market

messages:
  no-item-in-hand: "&c&l(!) &cYou must be holding an item in your main hand."
  reached-max-listings: "&c&l(!) &cYou can't list more than &7{max}&c items at a time!"
  list-item: "&aYou listed {amount}x {item}&a to the MarketPlace for ${price}!"
  sold-out: "&c&l(!) &cThat item has already been sold!"
  cant-afford: "&c&l(!) &cYou can't afford to buy that item!"
  cant-buy-from-yourself: "&c&l(!) &cYou can't buy items from yourself!"
  buy-cancel: "&cYou cancelled the purchase."
  buy-confirm: "&aYou purchased {amount}x {item}&a for ${price}!"
  your-item-sold: "&aYou earned ${money} for selling {amount}x {item}&a!"
  unlisted-item: "&cYou unlisted {amount}x {item}&c from the MarketPlace!"
  market-empty: "&cThere are no items listed on the MarketPlace."
  black-market-empty: "&cThere are no items listed on the Black Market right now. It will refresh in &7{time}&c."
  black-market-reset-broadcast: "&a[MarketPlace] The &7/blackmarket &ahas been refreshed!"

market-gui: # Regular Market Place GUI for item listings
  title: "MarketPlace &7({page}/{maxpages})"
  rows-per-page: 3
  next-page-icon: LIME_STAINED_GLASS_PANE
  previous-page-icon: LIME_STAINED_GLASS_PANE
  header-icon: BLACK_STAINED_GLASS_PANE # Icon that fills the top row
  next-page-text:
    - "&e&lNext Page --->"
  previous-page-text:
    - "&e&l<--- Previous Page"
  listing-text: # Added to the end of the lore of each item listing
    - " "
    - "&dSeller: &7{seller}"
    - "&6Price: &7${price}"
  my-listing-text: # Added to the end of the lore of your own item listings
    - " "
    - "&dSeller: &7{seller}"
    - "&6Price: &7${price}"
    - "&c&nClick to unlist this item"

my-listings-gui: # GUI showing your own listings
  title: "My Item Listings &7({page}/{maxpages})"
  rows-per-page: 3
  next-page-icon: LIME_STAINED_GLASS_PANE
  previous-page-icon: LIME_STAINED_GLASS_PANE
  header-icon: BLACK_STAINED_GLASS_PANE # Icon that fills the top row
  player-head-text: # Lore text for player head at top-center of GUI
    - "&e&n{player}'s MarketPlace Listings"
    - "&7Click an item to unlist"
    - "&7it from the MarketPlace."
    - "&7The item will be returned to you."
  next-page-text:
    - "&e&lNext Page --->"
  previous-page-text:
    - "&e&l<--- Previous Page"
  my-listing-text: # Added to the end of the lore of each item listing
    - " "
    - "&6Price: &7${price}"
    - "&c&nClick to unlist this item"

black-market-gui: # Black Market GUI for item listings
  title: "Black Market &7({page}/{maxpages})"
  rows-per-page: 3
  next-page-icon: LIME_STAINED_GLASS_PANE
  previous-page-icon: LIME_STAINED_GLASS_PANE
  header-icon: BLACK_STAINED_GLASS_PANE # Icon that fills the top row
  next-page-text:
    - "&e&lNext Page --->"
  previous-page-text:
    - "&e&l<--- Previous Page"
  listing-text: # Added to the end of the lore of each item listing
    - " "
    - "&dSeller: &7{seller}"
    - "&6Discounted Price: &7${price}"
  my-listing-text: # Added to the end of the lore of your own item listings
    - " "
    - "&dSeller: &7{seller}"
    - "&6Price: &7${price}"
    - "&c&nClick to unlist this item"

buy-confirm-gui:
  title: "Confirm your Purchase"
  rows: 3
  cancel-slot: 11 # Slot index for the cancel button
  confirm-slot: 15 # Slot index for the confirm button
  cancel-icon: RED_WOOL
  confirm-icon: LIME_WOOL
  filler-icon: BLACK_STAINED_GLASS_PANE # Icon that fills the gaps (AIR = no icon)
  cancel-text:
    - "&4&lCancel Purchase"
  confirm-text:
    - "&a&lConfirm Purchase"
    - " "
    - "&7{amount}x {item}"
    - "&6Price: &7${price}"

transactions-gui: # GUI for showing a player's transaction history
  title: "Transactions &7({page}/{maxpages})"
  rows-per-page: 3
  next-page-icon: LIME_STAINED_GLASS_PANE
  previous-page-icon: LIME_STAINED_GLASS_PANE
  header-icon: BLACK_STAINED_GLASS_PANE # Icon that fills the top row
  player-head-text: # Lore text for player head at top-center of GUI
    - "&a&n{player}'s Transactions"
    - " "
    - "&eTotal Purchases: &f{purchases}&7 (${moneyspent})"
    - "&6Total Sales: &f{sales}&7 (${moneyearned})"
  next-page-text:
    - "&e&lNext Page --->"
  previous-page-text:
    - "&e&l<--- Previous Page"
  bought-text: # Added to the end of the lore of each item you bought
    - " "
    - "&dSeller: &7{seller}"
    - "&6Bought For: &7${price}"
    - "&7{time}"
  sold-text: # Added to the end of the lore of each item you sold
    - " "
    - "&eBuyer: &7{buyer}"
    - "&6Sold For: &7${money}"
    - "&7{time}"