name: MarketPlace
version: '1.0'
main: me.uyuyuy99.marketplace.MarketPlace
api-version: '1.20'
depend:
  - Vault
permissions:
  marketplace.sell:
    description: Lists item in main hand for sale
    default: true
  marketplace.view:
    description: View the items for sale
    default: true
  marketplace.history:
    description: View your transaction history
    default: true